name: Tests

on:
  push:
    branches: [ "main" ]
    paths: [ "**.go", "go.mod" ]
  pull_request:
    branches: [ "main" ]
    paths: [ "**.go", "go.mod" ]

jobs:
  test:
    name: Unit Tests & Race Detector
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'

      - name: Run Tests
        run: go test -v -race -cover -shuffle=on ./...
